[package]
name = "ckrl"
version = "0.1.0"
authors = ["Chaanks <jarod8405@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.22"
glow = "0.4"


[lib]
name = "gckrl"
path = "src/lib.rs"

